# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_record_table_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='joke_comment',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
